spring:
  h2:
    console:
      enabled: true
  datasource:
    name: Drone
    driver-class-name: org.h2.Driver
    username: admin
    password: password
    url: jdbc:h2:mem:drone
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        check_nullability: True
    show-sql: true
logging:
  level:
    org:
      springframework:
        jdbc:
          DEBUG
server:
  servlet:
    context-path: /api
drone:
  setting:
    battery-threshold: 25
    fleet-capacity: 10
    initial-battery: 100