
spring:
  h2:
    console:
      enabled: true
  datasource:
    name: Drone
    driver-class-name: org.h2.Driver
    username: admin
    password: password
    url: jdbc:h2:mem:drone
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        check_nullability: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
logging:
  level:
    org:
      springframework:
        web:
          INFO
server:
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
drone:
  setting:
    battery-threshold: 25
    fleet-capacity: 10
    decay-rate: 0.05
    maximum-weight-limit: 500
scheduler:
  enable: true
  interval: 15