spring:
  h2:
    console:
      enabled: true
  datasource:
    name: Drone
    driver-class-name: org.h2.Driver
    username: admin
    password: password
    url: jdbc:h2:mem:drone

logging:
  level:
    org:
      springframework:
        jdbc:
          DEBUG